###
### Elasticsearch
###

version: "3.3"

networks:
  default:

services:
  elasticsearch:
    image: ${DOCKER_IMAGE}
    environment:
      - DOCKER_ENTRYPOINT_DEBUG=true
      - DOCKER_ENTRYPOINT_INFO=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.type=single-node
    networks:
      default:
        aliases:
          - elasticsearch.local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  test:
    image: ${TEST_IMAGE}
    command: ${TEST_CMD}
    depends_on:
      - elasticsearch
    env_file:
      - ${TEST_ENV_FILE}
    environment:
      - DOCKER_ENTRYPOINT_DEBUG=true
      - DOCKER_ENTRYPOINT_INFO=true
      - WAIT_FOR_TCP=elasticsearch.local:9200
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Use project dir as host volume for debugging tests if Docker host is local
      - ${TEST_PROJECT_DIR:-test_project_dir}:${PROJECT_DIR}
    working_dir: ${TEST_DIR}

  wait:
    image: ${TEST_IMAGE}
    depends_on:
      - elasticsearch
    environment:
      - DOCKER_ENTRYPOINT_DEBUG=true
      - DOCKER_ENTRYPOINT_INFO=true
      - WAIT_FOR_TCP=elasticsearch.local:9200
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  test_project_dir:
