###
### Elasticsearch with X-Pack
###

version: "3.3"

services:
  elasticsearch:
    depends_on:
      - simple_ca
    environment:
      - JAVA_TRUSTSTORE_PWD_FILE=/usr/share/elasticsearch/config/truststore.pwd
      - JAVA_KEYSTORE_PWD_FILE=/usr/share/elasticsearch/config/keystore.pwd
      - SERVER_CRT_HOST=${SERVER_CRT_HOST}
      - SIMPLE_CA_URL=https://simple-ca.local
      - XPACK_EDITION=platinum
      - XPACK_BOOTSTRAP_PASSWORD=changeme
      - xpack.security.http.ssl.enabled=true
    volumes:
      - simple_ca_secrets:/run/secrets:ro

  simple_ca:
    image: ${SIMPLE_CA_IMAGE}
    environment:
      - DOCKER_ENTRYPOINT_DEBUG=true
      - DOCKER_ENTRYPOINT_INFO=true
      - SERVER_CRT_HOST=simple-ca.local
    networks:
      default:
        aliases:
          - simple-ca.local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - simple_ca_data:/var/lib/simple-ca
      - simple_ca_secrets:/var/lib/simple-ca/secrets

  test:
    volumes:
      - simple_ca_secrets:/run/secrets:ro

volumes:
  simple_ca_data:
  simple_ca_secrets:
