version: 2
jobs:
  build:
    docker:
      - image: sicz/dockerspec
    environment:
      - MAKEFLAGS=--no-print-directory
      - RSPEC_FORMAT=doc
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.06.0-ce
      - run:
          name: Remote Docker engine version and images
          command: |
            docker --version
            docker-compose --version
            docker image ls
      - run:
          name: Checkout make files
          command: |
            cd ..
            curl -sSL https://github.com/SICZ/Mk/archive/master.tar.gz | tar -xzf -
            mv Mk-master Mk
      - run:
          name: sicz/elasticsearch:2.4.5
          working_directory: 2.4.5
          command: |
            make ci
      - run:
          name: sicz/elasticsearch:5.6.0
          working_directory: 5.6.0
          command: |
            make ci
      - run:
          name: sicz/elasticsearch:6.0.0
          working_directory: 6.0.0
          command: |
            make ci
      - deploy:
          name: Push images to the Docker Hub
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u ${DOCKER_HUB_USER} -p ${DOCKER_HUB_PASSWD}
              make docker-push
            fi
