### DOCKER_IMAGE ###############################################################

ELASTICSEARCH_VERSION	?= 5.6.1

DOCKER_IMAGE_TAGS	?= latest

### MK_DOCKER_IMAGE ############################################################

PROJECT_DIR		?= $(abspath ..)
include $(PROJECT_DIR)/docker.version.mk

################################################################################
